name: 'DCO Verification'

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  dco-assistant:
    uses: cordengine/.github/.github/workflows/dco-assistant.yml@main
    secrets:
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
