name: 'PR Open'

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  dco-assistant:
    uses: cordengine/.github/.github/workflows/dco-assistant.yml@main
